on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"
      - name: Change Version
        run: sed -i 's/mod_version=*/mod_version=${{ github.event.release.tag_name }}/g' gradle.properties
      - name: Build
        run: ./gradlew clean build
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-tag: "${{ github.event.release.tag_name }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

          name: "Robin's Apoli Additions v${{ github.event.release.tag_name }}"
          version: "${{ github.event.release.tag_name }}"
          version-type: "release"
          changelog: "${{ github.event.release.body }}"
          java: |
            17
